# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://qa.neapro.site/login/")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("bochkova69@mail.ru")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("3NHG3D3W")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(NaN)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".cabinet-page > .title")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mobile_menu__mobile-logo")
    assert len(elements) > 0
  
