# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://qa.neapro.site/cabinet/documents")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(2) > .document-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".outline").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("C:\\Users\\Сергей\\Desktop\\Penguins.jpg")
    self.driver.find_element(By.CSS_SELECTOR, ".fill").click()
    time.sleep(NaN)
    assert self.driver.find_element(By.CSS_SELECTOR, ".form-title").text == "Персональные данные"
  
